from django.conf.urls import patterns, url
from User.views import *

urlpatterns = patterns('',
                       url('^login', Login, name="login"),
                       url('^register/$', Register, name="register"),
                       url('^change_password', change_password, name="change_password"),
                       url('^logout/$', Logout, name="logout"),
                       url('^index', index, name="index"),
                       url('^upload/$', upload_file, name="upload"),
                       url('^download/$', download_file, name="download"),
                       url('^download_file/?file=(?P<file_id>\d+)/$', file_down_single, name="file_down_single"),
                       url('^delete_file/?file=(?P<file_id>\d+)/$', file_delete, name="file_delete"),
                       url('^delete_message/$', delete_message, name="delete_message"),
                       url('^share/$', share_file, name='share'),
                       url('^list/$', list_file, name='list'),
                       url('^file?.*/$', upload, name="test"),
                       url('^test_upload/$', test_upload, name="test_upload"),
                       url('^get_department/$', get_department, name="get_department"),
                       url('^improve_user_info/$', improve_user_info, name='improve_user_info'),
                       url('^get_department_multiple/$', get_department_multiple, name="get_department_multiple"),
                       url('^message_list/$', message_list, name="message_list"),
                       url('^upload_new_message/$', upload_new_message, name='upload_new_message'),
                       url('^upload_new_inline_message', upload_new_inline_message, name='upload_new_inline_message'),
                       url('^user_info_if_complete_authenticate/$', user_info_if_complete_authenticate,
                           name='user_info_if_complete_authenticate'),
                       )
